handle errors and have ability to explain them
soramitsu/Capital-iOS pull request #97
Opened 2020-10-19 14:03 UTC by ArsenyZ

старался сохранить максимум абстракции, но местами никак

2020-10-19 14:17 UTC, ifoatov approved these changes

2020-10-19 14:21 UTC, ERussel commented on CommonWallet/Core/Classes/Modules/OperationDefinition/OperationDefinitionViewController.swift
> +            (descriptionInputView?.viewModel?.isValid ?? true) && (receiverDef?.isValid ?? true)
валидность должна прилетать во view model и не зависеть от view, как мы обсудили

2020-10-19 14:22 UTC, ERussel commented on CommonWallet/Core/Classes/Modules/OperationDefinition/OperationDefinitionViewController.swift
> +    func presentReceiverError(_ message: String?, _ command: WalletCommandProtocol){
предлагаю сделать отдельную view model для ошибки как мы обсуждали

2020-10-19 14:24 UTC, ERussel commented on CommonWallet/Core/Classes/Modules/Transfer/TransferPresenter+ChangeHandling.swift
> +                if let command = errorMapping.command {
как и обсуждали лучше сделать отдельную view model для ошибки в которой и будет команда лежать. Она будет универсальная для всех, а не только для ресивера.

2020-10-19 14:24 UTC, ArsenyZ commented on CommonWallet/Core/Classes/Modules/OperationDefinition/OperationDefinitionViewController.swift
> +            (descriptionInputView?.viewModel?.isValid ?? true) && (receiverDef?.isValid ?? true)
Никак, валидность после создания выясняется

2020-10-19 19:18 UTC, ERussel requested changes
Предлагаю пока не мержить ПР, а продумать как передавать информацию об ошибках через VM

2021-01-12 13:11 UTC, ERussel commented on CommonWallet/Core/Classes/Modules/TransactionDetails/TransactionDetailsPresenter.swift
> +        let receiverInfo = transactionData.status != .rejected ?
I think that we just need to override the action itself. This implement is too specific to application

2021-01-18 10:48 UTC, ERussel approved these changes

2021-01-19 10:43 UTC, merged